version: '3.8'

services:
  app:
    build: .
    env_file: 
      - GAPi/DataBase.env
    ports:
      - "8080:8080"
    depends_on:
     db:
        condition: service_healthy  # Ждём, пока база будет готова

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: P
      POSTGRES_USER: postgres  
      POSTGRES_DB: gapim
    env_file: 
      - GAPi/DataBase.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gapim"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data: